### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#118]
Several ideas:
 - [x] publish a sitemap.xml See https://github.com/GFDRR/thinkhazard/issues/537
 - [x] have a robots.txt file 
 - [x] clean URLs - they clearly help - see https://github.com/GFDRR/thinkhazard/issues/116
 - [x] page title mentioning the admin division + hazard - see https://github.com/GFDRR/thinkhazard/issues/89
 - [ ] responsive design - see https://github.com/GFDRR/thinkhazard/issues/35

**Comment by pgiraud** [comment]
Responsive design is not scheduled for this version.
