### ISSUE TITLE
Implement offline  post-import checklist

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/thinkhazard#831]
Implement a post-data import checklist to ensure data is displaying as expected, to have formalised 'data sign off' of new data before publishing to public server. Sign off to be stored in an admin google sheet recording data imports.

To include
- [ ] data imported correctly (all columns as expected on Admin UI
- [ ] Data styled with appropriate metadata in Geonode, download functions correctly. Thumbnail shows correctly with basemap
- [ ] Data shows in TH UI map as expected, according to domain and data quality rating (relative to other layers). Checks to include data legend and styling.

set up a series of post-import checks: e.g., data used in TH, shows data in window as expected, downloads ok

**Comment by stufraser1** [comment]
UPDATE:
Focus of this issue was on ensuring the data displayed correctly in TH. This is more of a **manual check** by a TH admin, to be conducted in the ThinkHazard preview page, BEFORE publishing to public server. Sign off to be stored in an admin google sheet recording data imports.

Manual admin checklist includes:
- whether the data layer has been uploaded to TH correctly (this is shown in Admin page, and shows whether all mandatory metadata was included in the GeoNode layer, and whether RP layers in a hazard set match each other for extent, origin)
- in UI: check that the layer shows in regions where it is the highest-rated layer (checking data quality logic has worked as expected)
- in UI: Does data owner show correctly in the user interface
- in UI: is download / view permission and licence information correctly applied

**Comment by stufraser1** [comment]
Suggest this is written to the proposed Slate admin manual

**Comment by fjacon** [comment]
@MamadioCMCC I do not see here anything that needs to be done on ThinkHazard! as it looks like all these are manual check.
Do you confirm ?

**Comment by MamadioCMCC** [comment]
The original idea was to have a script to check the processing output; then, it turned into a manual check. Revising point by point, there are some minor adjustments that can be implemented on _TH side_ in order to help these issues.

> whether the data layer has been uploaded to TH correctly (this is shown in Admin page, and shows whether all mandatory metadata was included in the GeoNode layer

If we want to be sure that all important metadata are added, we may simply mark those as mandatory fields when uploading a layer (GeoNode side).

> and whether RP layers in a hazard set match each other for extent, origin)

This is partially already covered in the Admin page, "Complete" field (e.g. import issues with files are reported in red).

> in UI: check that the layer shows in regions where it is the highest-rated layer (checking data quality logic has worked as expected)

This should just work without need to check; _dataset map_ should also provide this information, allowing to check all at once.

> in UI: Does data owner show correctly in the user interface

Instead of checking output, the field should have char limit or _automatically truncate too long texts_.

> in UI: is download / view permission and licence information correctly applied

Again, if this works correctly by code there is no need to check it.

**Comment by pzwsk** [comment]
Not relevant with removal of Geonode and manual ingestion of hazard classifications
